name: Running internal tests

on:
  push:
    branches:
      - main
jobs:
  test:
    environment: vk-bot
    runs-on: ubuntu-latest

    steps:
      - name: install GO
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v2
      - name: Runs tests
        run: go test ./...


