# Default actions for deploy project
name: lint, test and deploy

on:
  push:
    branches:
      - main

jobs:
  # Lint go code
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  # Runs internal tests
  test:
    needs: lint
    environment: vk-bot # Default environment with variables
    runs-on: ubuntu-latest
    steps:
      - name: install GO
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - uses: actions/checkout@v2

      - name: Runs tests
        run: go test ./...
  # Build and push Docker image
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vk-bot:latest
  # Deploy on remote server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: vk-bot # Default environment with variables
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd vk-bot
            curl -O https://raw.githubusercontent.com/Volkov-D-A/vk-stitch-bot/main/docker-compose.yaml
            export API_URL=https://${{ secrets.SSH_HOST }}:{{ secrets.CALLBACK_PORT }}/callback