name: lint, test and deploy

on:
  push:
    branches:
      -main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  test:
    environment: vk-bot
    runs-on: ubuntu-latest
    steps:
      - name: install GO
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v2
      - name: Runs tests
        run: go test ./...